export const SET_LOGIN_USER = "SET_LOGIN_USER";
export const LOGOUT = "LOGOUT";
export const SET_SIDE_MENU = "SET_SIDE_MENU";
export const SET_ORDER_ITEMS_SYSTEM_1 = "SET_ORDER_ITEMS_SYSTEM_1";
export const SET_ORDER_ITEMS_SYSTEM_2 = "SET_ORDER_ITEMS_SYSTEM_2";
export const SET_ORDER_PAGE = "SET_ORDER_PAGE";
export const SET_ORDER_PAYLOAD = "SET_ORDER_PAYLOAD";
